# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only: master
    docker:
      # specify the version you desire here
      - image: circleci/node:11-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            # - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn test

      - run:
          name: Build the ~/app
          command: yarn build

      - run:
          name: Revoke current production static
          command: ssh -o StrictHostKeyChecking=no

      # эту комманду выполнить при первом вызове
      # - run:
      #     name: Copy code to production server
      #     command: scp -o StrictHostKeyChecking=no -rp ./build/* #ssh copy - scp

      - run:
          name: Copy code to production server
          command: scp -rp ./build/* #ssh copy - scp
